CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    full_name TEXT,
    question TEXT NOT NULL,
    department TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);